# Generated by Django 3.1.8 on 2021-04-17 05:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_easyai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlproject',
            name='pipeline_object',
        ),
        migrations.AddField(
            model_name='mlproject',
            name='preprocessing',
            field=wagtail.core.fields.StreamField([('knn_imputer', wagtail.core.blocks.StructBlock([('n_neighbors', wagtail.core.blocks.IntegerBlock(help_text='The number of neighbors to base the imputation on. Leave blank for sqrt(n)', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlproject',
            name='training',
            field=wagtail.core.fields.StreamField([('tpot_classifier', wagtail.core.blocks.StructBlock([('generations', wagtail.core.blocks.IntegerBlock(default=5, help_text='The number of evolutionary generations', min_value=0)), ('population_size', wagtail.core.blocks.IntegerBlock(default=20, help_text='The number of algorithms in each generation', min_value=0)), ('cv', wagtail.core.blocks.IntegerBlock(default=5, help_text='The number of folds to split your data into when cross validating. For example, a fold of 5 will test against each 1/5 of the data', label='Cross Validation Folds', min_value=0)), ('max_time_mins', wagtail.core.blocks.IntegerBlock(help_text='The number of minutes to train the model for (blank for until complete)', label='Train time', min_value=0, required=False)), ('verbosity', wagtail.core.blocks.IntegerBlock(default=2))]))], null=True),
        ),
        migrations.DeleteModel(
            name='MLPipeline',
        ),
    ]
